# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Felix Fontein <felix@fontein.de>

[collection_sources]

[sessions]

[sessions.lint]
run_isort = false
run_black = false
run_flake8 = false
run_pylint = false
run_yamllint = false
run_mypy = false

[sessions.docs_check]
validate_collection_refs="all"
codeblocks_restrict_types = [
    "ansible-output",
    "python",
    "yaml",
    "yaml+jinja",
]
codeblocks_restrict_type_exact_case = true
codeblocks_allow_without_type = false
codeblocks_allow_literal_blocks = false

[sessions.license_check]

[sessions.extra_checks]
run_no_unwanted_files = true
no_unwanted_files_module_extensions = [".py"]
no_unwanted_files_yaml_extensions = [".yml"]
run_action_groups = true
run_no_trailing_whitespace = true
run_avoid_characters = true

[[sessions.extra_checks.avoid_character_group]]
name = "tab"
regex = "\\x09"

[sessions.build_import_check]
run_galaxy_importer = true

[sessions.ansible_test_sanity]
include_devel = true
skip_tests = [
    "ansible-doc"
]

[sessions.ansible_test_units]
include_devel = true

[sessions.ansible_test_integration_w_default_container]
include_devel = true

[sessions.ansible_test_integration_w_default_container.core_python_versions]
"2.9" = ["2.7", "3.5"]
"2.10" = ["3.5"]
"2.11" = ["2.6"]
"2.12" = ["2.6", "3.8"]
"2.13" = ["2.7", "3.9"]
"2.14" = ["3.10"]
"2.15" = ["3.5"]
"2.16" = ["3.6"]
"2.17" = ["3.7"]
"2.18" = ["3.8"]
"2.19" = ["3.9"]
