# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2022, Felix Fontein

namespace: felixfontein
name: playground
version: 0.0.1
readme: README.md
authors:
  - Felix Fontein (https://github.com/felixfontein)
description: null
license_file: COPYING
tags: [felixfontein]
dependencies: {}
repository: https://github.com/felixfontein/ansible-playground
homepage: https://github.com/felixfontein/ansible-playground
issues: https://github.com/felixfontein/ansible-playground/issues
build_ignore:
  - 'felixfontein-playground-*.tar.gz'
