objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi: {}
  inventory: {}
  lookup:
    dependent:
      description: Composes a list with nested elements of other lists or dicts which
        can depend on previous indices
      name: dependent
      version_added: 1.0.0
  module:
    wait_for_txt:
      description: Wait for TXT entries to be available on all authoritative nameservers
      name: wait_for_txt
      namespace: ''
      version_added: 1.4.0
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.5.0
